module.exports = {
  preset: 'ts-jest',
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  testEnvironment: 'node',
  moduleDirectories: ['node_modules', 'src'],
  moduleNameMapper: {
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@modules/(.*)$': '<rootDir>/modules/$1',
    '^@app/(.*)$': '<rootDir>/app/$1',
    '^@generated/(.*)$': '<rootDir>/app/$1',
  },

  collectCoverageFrom: ['<rootDir>/modules/**/*.ts'],
  coverageDirectory: '../coverage',
  coveragePathIgnorePatterns: [
    '/node_modules/',
    'common',
    '<rootDir>/main.ts',
    'index.ts',
    'jestGlobalMocks.ts',
    '.interface.ts',
    '.module.ts',
    '.mock.ts',
    '.model.ts',
    '.entity.ts',
    '.dto.ts',
    '.input.ts',
    '.spec.ts',
    '.test.ts',
    '.decorator.ts',
    '.types.ts',
  ],
};
