module.exports = {
  preset: 'ts-jest',
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  testEnvironment: 'node',
  moduleDirectories: ['node_modules', 'src'],
  moduleNameMapper: {
    '@common/(.*)': '<rootDir>/common/$1',
    '@modules/(.*)': '<rootDir>/modules/$1',
    '@app/(.*)': '<rootDir>/app/$1',
  },

  collectCoverageFrom: ['<rootDir>/modules/**/*.ts'],
  coverageDirectory: '../coverage',
  coveragePathIgnorePatterns: [
    'node_modules',
    'test-config',
    'interfaces',
    '.interface.ts',
    'jestGlobalMocks.ts',
    '.module.ts',
    '<rootDir>/main.ts',
    '.mock.ts',
    '.model.ts',
    '.entity.ts',
    '.dto.ts',
    'index.ts',
    '.input.ts',
    '.spec.ts',
    '.test.ts',
    '.gitkeep',
    '.decorator.ts',
    '.types.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 20,
      functions: 30,
      lines: 50,
      statements: 50,
    },
  },
};
