export const REDIS_CONFIRM_USER_PREFIX = 'USER_CONFIRMATION:';
export const REDIS_FORGOT_PASSWORD_PREFIX = 'REQUEST_FORGOT_PASSWORD:';
export const REDIS_KEY_SESSION = 'AUTH_SESSION_ID';
export const REDIS_CONFIG_OPTS = 'REDIS_CONFIG_OPTS';
