export const REDIS_CONFIRM_USER_PREFIX = 'USER_CONFIRMATION:';
export const REDIS_FORGOT_PASSWORD_PREFIX = 'REQUEST_FORGOT_PASSWORD:';
export const REDIS_AUTH_TOKEN_SESSION = 'AUTH_TOKEN_SESSION';
export const REDIS_CONFIG_OPTS = 'REDIS_CONFIG_OPTS';
